### ISSUE TITLE
Possible to select key at runtime?

### ISSUE THREAD

**Issue by jenniferplusplus** [Unisys/NSign#18]
I'm developing an activitypub service, and http signatures have come to form the basis of federated authentication in that space. NSign looks great, and I would really like to use it. But, I have one major question. All of the examples specify a signing key at startup time. But I would need to sign requests with individual user account keys, which need to be looked up at run time. Is there an easy way to provide those keys at run time, instead?

**Comment by rogerk-unifysquare** [comment]
Hi,

that's an excellent question. It should actually be pretty straightforward to achieve, through a custom `ISigner` implementation. For instance, if you're building a web service that sends signed requests based on a key for the user making e.g. an API request, a class like the following should do the trick:

```csharp
internal sealed class UserBasedSignatureProvider : ISigner
{
    private static readonly Encoding UTF8 = new UTF8Encoding();
    private readonly IHttpContextAccessor httpContextAccessor;

    public UserBasedSignatureProvider(IHttpContextAccessor httpContextAccessor)
    {
        this.httpContextAccessor = httpContextAccessor;
    }

    public Task<ReadOnlyMemory<byte>> SignAsync(ReadOnlyMemory<byte> input, CancellationToken cancellationToken)
    {
        ISigner signer = GetSignerForUser();
        try
        {
            return signer.SignAsync(input, cancellationToken);
        }
        finally
        {
            if (signer is IDisposable disposable)
            {
                disposable.Dispose();
            }
        }
    }

    public void UpdateSignatureParams(SignatureParamsComponent signatureParams)
    {
        string username = GetUserName();
        ISigner signer = GetSignerForUser(username);
        try
        {
            signer.UpdateSignatureParams(signatureParams);
            signatureParams.Tag = $"user[{username}]";
        }
        finally
        {
            if (signer is IDisposable disposable)
            {
                disposable.Dispose();
            }
        }
    }

    private string GetUserName()
    {
        return httpContextAccessor.HttpContext?.User?.Identity?.Name ?? "no-user";
    }

    private ISigner GetSignerForUser(string? username = null)
    {
        if (null == username)
        {
            username = GetUserName();
        }

        return new HmacSha256SignatureProvider(UTF8.GetBytes(username), username);
    }
}
```

This implementation can be registered for dependency injection like this:
```csharp
services
    .AddHttpContextAccessor() // Needed to get IHttpContextAccessor
    .AddTransient<ISigner, UserBasedSignatureProvider>();
```

What this class does:

1. It uses the `IHttpContextAccessor` to get access to the current HTTP request (if any) and its user.
2. It delegates creating a signature to an instance of `ISigner` that was created/retrieved for the user from the HTTP context. Those `ISigner` instance could also be cached.
3. It also updates the `keyid` and `tag` parameters of the signature to be based off the user's name/ID.

This implementation is obviously not very meaningful from a security PoV (the HMAC secret is the same as the user name), but it shows that one can select a specific signature algorithm with its own key at runtime.

If you don't sign and send requests in response to a user request, all you need to do is pass the user information e.g. through a scoped service in dependency injection, and use that user information to look up the correct signature algorithm and key.

I hope this helps. I should be able to provide an actual example later today or this week.

**Comment by rogerk-unifysquare** [comment]
Btw, AFAIK ActivityPub uses a very old version of HTTP signatures from 2017/2018. On the other hand, NSign is targeting the [latest draft](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-message-signatures) which replaced the old draft and is significantly different. Accordingly, your mileage for ActivityPub with NSign will vary and NSign may not actually help you much.

**Comment by jenniferplusplus** [comment]
Thank you, I think that will work for me. I had to do something a little more complicated, because the client isn't guaranteed to be in an http request context. But, the basic strategy works. You can close this issue if you want.

Following up on the specifics of activitypub, are you open to contributions that would make it easier to support that use case? It looks like you have a visitor pattern for building the message base, which I think makes this a relatively straightforward enhancement. I'm imagining the visitor could be given an instance of an IFormatter to modify how the base is structured. This is something I'll have to explore either way, but I would be more than happy to contribute it back if you want.

**Comment by rogerk-unifysquare** [comment]
Closing this as per the above statements.
Additional discussion happening in #19
