### ISSUE TITLE
Content-Digest header format doesn't comply with RFC 9530

### ISSUE THREAD

**Issue by nha** [Unisys/NSign#66]
I believe the content-digest component is not compliant with the RFC 9530.

- uppercase hashing algorithm name (`SHA-512`) when it should be lowercase (`sha-512`)
- missing colons `:` around the base64 value.

Example [from the RFC](https://datatracker.ietf.org/doc/html/rfc9530#name-the-content-digest-field) (minus line-wrapping)
>  Content-Digest: sha-512=:YMAam51Jz/jOATT6/zvHrLVgOYTGFy1d6GJiOHTohq4yP+pgk4vf2aCsyRZOtw8MjkM7iw7yZ/WkppmM44T3qg==:

Versus what NSign would send
>  Content-Digest: SHA-512=YMAam51Jz/jOATT6/zvHrLVgOYTGFy1d6GJiOHTohq4yP+pgk4vf2aCsyRZOtw8MjkM7iw7yZ/WkppmM44T3qg==

**Comment by rogerk-unifysquare** [comment]
Thanks for bringing this to my attention, @nha . You're absolutely right, I missed this after the release of RFC 9421 in February. I'll be working on a fix for this - stay tuned.

**Comment by rogerk-unifysquare** [comment]
Release [v1.1.0](https://github.com/Unisys/NSign/releases/tag/v1.1.0) should address this.

Please re-open if you feel this is still an issue.
