### ISSUE TITLE
I seem to not find everywhere the RequestSigningOptions class, where is it?

### ISSUE THREAD

**Issue by thepra** [Unisys/NSign#9]
I've been followind the example but this is the only class that I can't find in any package.

**Comment by rogerk-unifysquare** [comment]
My apologies, with one of the recent updates, the `RequestSigningOptions` has been replaced with the more generic `MessageSigningOptions`. You can use the `ConfigureMessageSigningOptions` extension method to configure it. The example has been updated accordingly.

**Comment by thepra** [comment]
Thanks for the update, given the chance, could you write an example of adding an HttpClient(that later I could get from the factory) that signs the requests upon sending?

**Comment by rogerk-unifysquare** [comment]
@thepra, let me start by clarifying that it is _not_ the `HttpClient` that signs messages or verifies signatures on responses. In both cases, it's a message handler that does that as part of the request middleware pipeline of the client.

* For signing of outgoing requests, the [`SigningHandler`](https://github.com/Unisys/NSign/blob/main/src/NSign.Client/Client/SigningHandler.cs) is used; see https://github.com/Unisys/NSign/blob/main/src/NSign.Client/DependencyInjectionExtensions.cs#L39-L43 for where this is set up on the `IHttpClientBuilder`.
* For verifying signatures of incoming responses, the [`SignatureVerificationHandler`](https://github.com/Unisys/NSign/blob/main/src/NSign.Client/Client/SignatureVerificationHandler.cs) is used; see https://github.com/Unisys/NSign/blob/main/src/NSign.Client/DependencyInjectionExtensions.cs#L74-L78 for where this is set up on the `IHttpClientBuilder`.

The so configured `HttpClient` can be injected through dependency injection as usual. In the example in the README.md, we've used a [typed client](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-6.0#typed-clients) (implementation `Caller` of the `ICaller` interface), but really any way you configure your HTTP client and its middleware, and inject it in your logic will do. For instance, the following skeleton class could be used to implement `ICaller` (whatever that interface requires) and use the `HttpClient` configured to sign request messages:

```csharp
internal sealed class Caller : ICaller
{
    private readonly HttpClient client;

    public Caller(HttpClient client)
    {
        this.client = client;
    }

    // Actual logic using 'client' goes here ...
}
```

But for the same example, using the `IHttpClientFactory` and passing `"WebhooksCaller"` as the name to be used with the `CreateClient` method will give you a client with request message signing too. The key really is in the configuration of the message handlers for the client.

Hope this helps.
